name: bigkart
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^1.0.2
  location: ^3.0.2
  woocommerce: ^0.9.7
  provider: ^5.0.0
  shimmer: ^1.1.2
  liquid_swipe: ^2.0.1
  google_maps_flutter: ^1.0.3
  custom_radio_grouped_button: ^1.0.6+1
  bottom_navy_bar: ^5.4.0
  popup_menu: ^1.0.5
  url_launcher: ^5.5.2
  get_it: ^1.0.3+2
  country_state_city_picker: ^1.2.7
  curved_navigation_bar: ^0.3.3
  permission_handler: ^5.0.0
  contacts_service: ^0.3.10
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  wc_form_validators: ^0.1.1
  fluttertoast: ^7.0.2
  shared_preferences : ^0.5.8
  rflutter_alert: ^1.0.3
  rich_alert: ^0.1.32
  extended_image: ^0.5.6
  image_cropper: ^1.3.1
  getwidget: ^1.2.4
  flutter_open_whatsapp: ^0.1.2
  camera:
  path_provider:
  path:
  image_picker: ^0.6.6+5
  group_radio_button: ^1.0.1
  simple_animations: ^1.3.3
  device_info: ^0.4.2+8
  carousel_slider: ^2.3.1
  progress_dialog: ^1.2.4
  flutter_mobile_vision: ^0.1.4+1
  flutter_parsed_text: ^1.2.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:









    flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true


  assets:
    - assets/imgapp/bg.png
    - assets/imgapp/cart.png
    - assets/imgapp/bg.jpg
    - assets/imgapp/icn5.png
    - assets/imgapp/icn6.png
    - assets/imgapp/icn7.png
    - assets/imgapp/icn8.png
    - assets/imgapp/icn9.png
    - assets/imgapp/bgaa.png
    - assets/imgapp/order.png
    - assets/imgapp/bg.jpg
    - assets/imgapp/onbd1.png
    - assets/imgapp/onbd2.jpg
    - assets/imgapp/onbd3.jpg
    - assets/imgapp/onbd2.png
    - assets/imgapp/onbg3.png
    - assets/images/logo.png
    - assets/images/logokmb.png
    - assets/images/clock.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/background.png
    - assets/images/backgroundf.png
    - assets/images/backgroundsignup.png
    - assets/images/backgroundwlcm.png
    - assets/images/logo.jpg
    - assets/images/logow.jpg
    - assets/images/powered_by.png
    - assets/images/icon_list.png
    - assets/images/scene1.png
    - assets/images/scene2.png
    - assets/images/scene3.png
    - assets/images/scene4.png
    - assets/images/scene5.png
    - assets/images/scene6.png
    - assets/images/success.png
    - assets/images/delete.png
    - assets/images/logokmc.jpg
    - assets/images/designlogos.png
    - assets/images/marsqwe.png
    - assets/images/ecard.jpg
    - assets/images/onboarding0.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/premiun.jpeg
    - assets/images/caed.png



  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/Product_Sans_Bold.ttf
        - asset: assets/font/Product_Sans_Regular.ttf
